---
version: '3.9'

services:
  kafka:
    image: confluentinc/confluent-local:7.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
    healthcheck:
      test: [ "CMD", "echo", "hello", "|", "nc", "-zv", "localhost", "29092" ]
      interval: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    healthcheck:
      test: nc -z schema-registry 8081 || exit -1
      interval: 2s
      retries: 5
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

  kafka-rest:
    image: confluentinc/cp-kafka-rest:7.2.1
    hostname: kafka-rest
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    healthcheck:
      test: curl --fail http://kafka-rest:8082 || exit 1
      interval: 2s
      retries: 5
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
